# Generated by Django 3.2.11 on 2022-03-07 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('bit_rate', models.CharField(choices=[('normal', 'normal'), ('high', 'high'), ('low', 'low')], default='normal', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usersoundsettings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sound Setting',
                'verbose_name_plural': 'Sound Settings',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
