# Generated by Django 3.2.12 on 2022-03-22 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_alter_playlist_podcast'),
        ('tunes', '0003_stations_slug'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('stations', models.ManyToManyField(blank=True, related_name='stations', to='tunes.Stations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favoritestation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Station',
                'verbose_name_plural': 'Favorite Stations',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FavoritePodcasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('podcasts', models.ManyToManyField(blank=True, related_name='podcasts', to='podcast.Podcast')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favoritepodcast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Podcast',
                'verbose_name_plural': 'Favorite Podcasts',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
