# Generated by Django 3.2.11 on 2022-03-14 09:42

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_follower'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('managers', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
