# Generated by Django 3.2.12 on 2022-03-18 00:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import radio_funk.utils.storages
import stdimage.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('description', tinymce.models.HTMLField(verbose_name='Tune Description')),
                ('logo', stdimage.models.StdImageField(blank=True, upload_to=radio_funk.utils.storages.get_radio_upload_folder)),
                ('stream_url', models.URLField()),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='+(902) 420-8311', max_length=20, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('active', models.BooleanField(default=False)),
                ('country', models.ForeignKey(default='US', on_delete=django.db.models.deletion.CASCADE, to='countries_plus.country')),
            ],
            options={
                'verbose_name': 'Radio Upload',
                'verbose_name_plural': 'Radio Uploads',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
