# Generated by Django 3.2.11 on 2022-02-08 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('tunes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunes',
            name='country',
            field=models.ForeignKey(default='US', on_delete=django.db.models.deletion.CASCADE, to='countries_plus.country'),
        ),
        migrations.RemoveField(
            model_name='tunes',
            name='genre',
        ),
        migrations.AddField(
            model_name='tunes',
            name='genre',
            field=models.ManyToManyField(to='tunes.Genre'),
        ),
    ]
