# Generated by Django 3.2.11 on 2022-02-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0002_auto_20220207_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunes',
            name='address',
            field=models.TextField(default='P.O. Box 3000 Halifax, NS B3J 3E9'),
        ),
        migrations.AddField(
            model_name='tunes',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tunes',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tunes',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
