# Generated by Django 3.2.11 on 2022-02-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0003_auto_20220207_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunes',
            name='phone',
            field=models.CharField(blank=True, default='+(902) 420-8311', max_length=14, null=True),
        ),
    ]
