# Generated by Django 3.2.11 on 2022-03-07 17:57

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('description', tinymce.models.HTMLField(verbose_name='Genre Description')),
            ],
            options={
                'verbose_name': 'Podcast & Radio Genre',
                'verbose_name_plural': 'Podcast & Radio Genres',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
