# Generated by Django 3.2.12 on 2022-03-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
