# Generated by Django 3.2.11 on 2022-03-07 17:57

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ip', models.CharField(max_length=500, unique=True)),
                ('theme', models.CharField(choices=[('dark', 'dark'), ('light', 'light')], default='light', max_length=10)),
            ],
            options={
                'verbose_name': 'Dark or Light Theme',
                'verbose_name_plural': 'Dark or Light Themes',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
