# Generated by Django 3.2.11 on 2022-03-07 19:51

import django.core.validators
from django.db import migrations, models
import radio_funk.utils.storages


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='audio',
            field=models.FileField(blank=True, upload_to=radio_funk.utils.storages.get_norm_audio_upload_folder, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])], verbose_name='AudioFile'),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='audio_high',
            field=models.FileField(blank=True, upload_to=radio_funk.utils.storages.get_hi_audio_upload_folder, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])], verbose_name='AudioFile_hi'),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='audio_min',
            field=models.FileField(blank=True, upload_to=radio_funk.utils.storages.get_lo_audio_upload_folder, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])], verbose_name='AudioFile_lo'),
        ),
    ]
