# Generated by Django 3.2.11 on 2022-03-08 18:14

import django.core.validators
from django.db import migrations, models
import radio_funk.utils.storages


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20220307_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodes',
            name='audio_high',
        ),
        migrations.RemoveField(
            model_name='episodes',
            name='audio_min',
        ),
        migrations.AlterField(
            model_name='episodes',
            name='audio',
            field=models.FileField(blank=True, upload_to=radio_funk.utils.storages.get_norm_audio_upload_folder, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])], verbose_name='AudioFile'),
        ),
    ]
