# Generated by Django 3.2.11 on 2022-03-11 17:22

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcast', '0003_auto_20220308_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'Episode Gift',
                'verbose_name_plural': 'Episode Gifts',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique='True', verbose_name='slug')),
                ('description', tinymce.models.HTMLField(verbose_name='Playlist Description')),
                ('private', models.BooleanField(default=False)),
                ('like', models.ManyToManyField(related_name='playlist_likes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='playlist_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Podcast Playlist',
                'verbose_name_plural': 'Podcast Playlists',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='episodes',
            name='like',
            field=models.ManyToManyField(related_name='podcast_episode_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast',
            name='like',
            field=models.ManyToManyField(related_name='podcast_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='title'),
        ),
        migrations.DeleteModel(
            name='PodcastGift',
        ),
        migrations.AddField(
            model_name='playlist',
            name='podcast',
            field=models.ManyToManyField(to='podcast.Podcast'),
        ),
        migrations.AddField(
            model_name='episodegift',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='episode_gift', to='podcast.episodes'),
        ),
        migrations.AddField(
            model_name='episodegift',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gift', to='podcast.gift'),
        ),
        migrations.AddField(
            model_name='episodegift',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gifter', to=settings.AUTH_USER_MODEL),
        ),
    ]
