# Generated by Django 3.2.11 on 2022-03-12 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcast', '0004_auto_20220311_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, related_name='podcast_episode_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, related_name='playlist_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, related_name='podcast_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
