# Generated by Django 3.2.11 on 2022-03-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_auto_20220315_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='explicit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'yes'), (2, 'no'), (3, 'clean'), (4, 'kids')], default=1, help_text='Audience this content should be shown to. Explicit determines this episode not being shown to viewers under 18 years of age.', verbose_name='explicit'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='author_text',
            field=models.CharField(help_text="\n            This tag contains the name of the person or company that is most\n            widely attributed to publishing the Podcast and will be\n            displayed immediately underneath the title of the Podcast.\n            The suggested format is: 'email@example.com (Full Name)'\n            but 'Full Name' only, is acceptable. Multiple authors\n            should be comma separated.", max_length=255, verbose_name='Featured Personalities'),
        ),
    ]
