# Generated by Django 3.2.11 on 2022-03-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_auto_20220315_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='published',
        ),
        migrations.AddField(
            model_name='podcast',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
    ]
