# Generated by Django 3.2.11 on 2022-03-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0008_auto_20220315_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='explicit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'yes'), (2, 'no'), (3, 'clean'), (4, 'kids')], default=2, help_text='Audience this content should be shown to. Explicit determines this episode not being shown to viewers under 18 years of age.', verbose_name='explicit'),
        ),
    ]
